



libname omar "C:\Users\orodriguez.AUTOTRADER\Desktop\7_Lead_Gen_Model\from_gloria";


/**Import data**/
/**
proc import 
datafile='C:\Users\orodriguez.AUTOTRADER\Desktop\7_Lead_Gen_Model\from_gloria\new_veh_lead_gen_feed.csv'
out=omar.new_lead
dbms=csv;
GUESSINGROWS=32767;
RUN;
proc contents data=omar.new_lead varnum; run;
**/



proc import 
datafile='C:\Users\orodriguez.AUTOTRADER\Desktop\7_Lead_Gen_Model\from_gloria\used_veh_lead_gen_feed.csv'
out=omar.used_lead
dbms=csv;
GUESSINGROWS=32767;
RUN;
proc contents data=omar.used_lead varnum; run;




%let datasource=omar.new_lead;


/**Obtain variable names**/
proc contents data=&datasource out=datavars; run;



/**Obtain the number of counts (observations/records) for each variable**/
proc sql;
create table t_resp as
select count(ALPHA_IMPRESSION_CNT) as ALPHA_IMPRESSION_CNT,
count(ALPHA_SESSION_CNT) as ALPHA_SESSION_CNT,
count(ATC_DETAIL_PAGE_CNT) as ATC_DETAIL_PAGE_CNT,
count(ATC_IND) as ATC_IND,
count(AVG_COMMENTS_LENGTH) as AVG_COMMENTS_LENGTH,
count(AVG_MSRP) as AVG_MSRP,
count(AVG_PRICE) as AVG_PRICE,
count(AVG_PRICE_TO_MARKET_INDEX) as AVG_PRICE_TO_MARKET_INDEX,
count(AVG_SCARCITY_INDEX) as AVG_SCARCITY_INDEX,
count(BODYSTYLE_NAME) as BODYSTYLE_NAME,
count(BRAND_SEM_IMPRESSION_CNT) as BRAND_SEM_IMPRESSION_CNT,
count(BRAND_SEM_SESSION_CNT) as BRAND_SEM_SESSION_CNT,
count(BUSINESS_ELITE_IND) as BUSINESS_ELITE_IND,
count(CAR_BASE_SRP_IMPRESSION_CNT) as CAR_BASE_SRP_IMPRESSION_CNT,
count(CAR_DETAIL_PAGE_CNT) as CAR_DETAIL_PAGE_CNT,
count(CAR_DURABLE_KEY) as CAR_DURABLE_KEY,
count(CAR_ID) as CAR_ID,
count(CAR_SPOTLIGHT_IMPRESSION_CNT) as CAR_SPOTLIGHT_IMPRESSION_CNT,
count(CAR_SRP_IMPRESSION_CNT) as CAR_SRP_IMPRESSION_CNT,
count(CERTIFIED_IND) as CERTIFIED_IND,
count(CHAT) as CHAT,
count(COMPUTER_IMPRESSION_CNT) as COMPUTER_IMPRESSION_CNT,
count(CREDIT_APP) as CREDIT_APP,
count(CUSTOMER_DURABLE_KEY) as CUSTOMER_DURABLE_KEY,
count(D_NEW_CAR_MERCHANDISING_SCORE) as D_NEW_CAR_MERCHANDISING_SCORE,
count(D_USED_CAR_MERCHANDISING_SCORE) as D_USED_CAR_MERCHANDISING_SCORE,
count(DEALER_MERCHANDISING_SCORE) as DEALER_MERCHANDISING_SCORE,
count(DIRECT_IMPRESSION_CNT) as DIRECT_IMPRESSION_CNT,
count(DIRECT_SESSION_CNT) as DIRECT_SESSION_CNT,
count(DMA) as DMA,
count(DR_MEDIA_IMPRESSION_CNT) as DR_MEDIA_IMPRESSION_CNT,
count(DR_MEDIA_SESSION_CNT) as DR_MEDIA_SESSION_CNT,
count(EMAILS) as EMAILS,
count(FRONT_LINE_LISTING_IND) as FRONT_LINE_LISTING_IND,
count(FRONT_LINE_PRO_IND) as FRONT_LINE_PRO_IND,
count(HP_IMPRESSION_CNT) as HP_IMPRESSION_CNT,
count(HP_SESSION_CNT) as HP_SESSION_CNT,
count(IMAGE_FLG) as IMAGE_FLG,
count(INCENTIVE_PRICE) as INCENTIVE_PRICE,
count(INCENTIVE_PRICE_IND) as INCENTIVE_PRICE_IND,
count(INTEREST_EVENTS_1) as INTEREST_EVENTS_1,
count(INTEREST_EVENTS_2) as INTEREST_EVENTS_2,
count(KBB_IND) as KBB_IND,
count(KBB_PHOTO_FLG) as KBB_PHOTO_FLG,
count(LEAD_1) as LEAD_1,
count(LEAD_2) as LEAD_2,
count(LISTING_COMMENTS_IND) as LISTING_COMMENTS_IND,
count(LISTING_DURABLE_KEY) as LISTING_DURABLE_KEY,
count(LISTING_TYPE) as LISTING_TYPE,
count(MAKE_NAME) as MAKE_NAME,
count(MAP) as MAP,
count(MAX_DAYS_ON_SITE) as MAX_DAYS_ON_SITE,
count(MAX_MILEAGE) as MAX_MILEAGE,
count(MOBILE_FYC_DETAIL_PAGE_CNT) as MOBILE_FYC_DETAIL_PAGE_CNT,
count(MOBILE_FYC_SRP_IMPRESSION_CNT) as MOBILE_FYC_SRP_IMPRESSION_CNT,
count(MODEL_NAME) as MODEL_NAME,
count(MODEL_YEAR) as MODEL_YEAR,
count(NEW_IND) as NEW_IND,
count(NON_BRAND_SEM_IMPRESSION_CNT) as NON_BRAND_SEM_IMPRESSION_CNT,
count(NON_BRAND_SEM_SESSION_CNT) as NON_BRAND_SEM_SESSION_CNT,
count(OTHER_EP_IMPRESSION_CNT) as OTHER_EP_IMPRESSION_CNT,
count(OTHER_EP_SESSION_CNT) as OTHER_EP_SESSION_CNT,
count(OTHER_SOT_IMPRESSION_CNT) as OTHER_SOT_IMPRESSION_CNT,
count(OTHER_SOT_SESSION_CNT) as OTHER_SOT_SESSION_CNT,
count(OTHERLSTG_IMPRESSION_CNT) as OTHERLSTG_IMPRESSION_CNT,
count(OTHERLSTG_SESSION_CNT) as OTHERLSTG_SESSION_CNT,
count(OWNER_ID) as OWNER_ID,
count(PARTNERSHIP_IMPRESSION_CNT) as PARTNERSHIP_IMPRESSION_CNT,
count(PARTNERSHIP_SESSION_CNT) as PARTNERSHIP_SESSION_CNT,
count(PAYMENT_OFFERS_IND) as PAYMENT_OFFERS_IND,
count(PAYMENT_ON_LISTING_IND) as PAYMENT_ON_LISTING_IND,
count(PHONE_IMPRESSION_CNT) as PHONE_IMPRESSION_CNT,
count(PHONE_LOOKUP) as PHONE_LOOKUP,
count(POTENTIAL_SALE) as POTENTIAL_SALE,
count(PRINT) as PRINT,
count(PRIVATE_SELLER_FLAG) as PRIVATE_SELLER_FLAG,
count(RN) as RN,
count(SAVES) as SAVES,
count(SEO_IMPRESSION_CNT) as SEO_IMPRESSION_CNT,
count(SEO_SESSION_CNT) as SEO_SESSION_CNT,
count(SESSION_CNT) as SESSION_CNT,
count(SF_IMPRESSION_CNT) as SF_IMPRESSION_CNT,
count(SF_SESSION_CNT) as SF_SESSION_CNT,
count(SPIN360_FLAG) as SPIN360_FLAG,
count(SPOTLIGHT_IMPRESSION_CNT) as SPOTLIGHT_IMPRESSION_CNT,
count(SPOTLIGHT_IND) as SPOTLIGHT_IND,
count(SPOTLIGHT_SESSION_CNT) as SPOTLIGHT_SESSION_CNT,
count(SRP_ALP_IMPRESSION_FLG) as SRP_ALP_IMPRESSION_FLG,
count(SRP_ALPHA_IMPRESSION_CNT) as SRP_ALPHA_IMPRESSION_CNT,
count(SRP_ALPHA_SESSION_CNT) as SRP_ALPHA_SESSION_CNT,
count(SRP_IMPRESSION_CNT) as SRP_IMPRESSION_CNT,
count(SRP_OTH_IMPRESSION_FLG) as SRP_OTH_IMPRESSION_FLG,
count(SRP_OTHERLSTG_IMPRESSION_CNT) as SRP_OTHERLSTG_IMPRESSION_CNT,
count(SRP_OTHERLSTG_SESSION_CNT) as SRP_OTHERLSTG_SESSION_CNT,
count(SRP_SESSION_CNT) as SRP_SESSION_CNT,
count(SRP_SP_IMPRESSION_FLG) as SRP_SP_IMPRESSION_FLG,
count(SRP_SPOTLIGHT_IMPRESSION_CNT) as SRP_SPOTLIGHT_IMPRESSION_CNT,
count(SRP_SPOTLIGHT_SESSION_CNT) as SRP_SPOTLIGHT_SESSION_CNT,
count(SRP_VLIST_IMPRESSION_CNT) as SRP_VLIST_IMPRESSION_CNT,
count(SRP_VLIST_IMPRESSION_FLG) as SRP_VLIST_IMPRESSION_FLG,
count(SRP_VLIST_SESSION_CNT) as SRP_VLIST_SESSION_CNT,
count(TABLET_IMPRESSION_CNT) as TABLET_IMPRESSION_CNT,
count(TOTAL_IMP) as TOTAL_IMP,
count(TOTAL_SRPI) as TOTAL_SRPI,
count(VARIANCE_BUCKET) as VARIANCE_BUCKET,
count(VDP) as VDP,
count(VDP_ALPHA_IMP_FLG) as VDP_ALPHA_IMP_FLG,
count(VDP_BRAND_SEM_ENTRY) as VDP_BRAND_SEM_ENTRY,
count(VDP_COMPUTER_ENTRY) as VDP_COMPUTER_ENTRY,
count(VDP_DIRECT_ENTRY) as VDP_DIRECT_ENTRY,
count(VDP_DR_MEDIA_ENTRY) as VDP_DR_MEDIA_ENTRY,
count(VDP_HP_ENTRY) as VDP_HP_ENTRY,
count(VDP_IMPRESSION_CNT) as VDP_IMPRESSION_CNT,
count(VDP_NON_BRAND_SEM_ENTRY) as VDP_NON_BRAND_SEM_ENTRY,
count(VDP_OTHER_EP_ENTRY) as VDP_OTHER_EP_ENTRY,
count(VDP_OTHER_SOT_ENTRY) as VDP_OTHER_SOT_ENTRY,
count(VDP_OTHERLSTG_IMP_FLG) as VDP_OTHERLSTG_IMP_FLG,
count(VDP_PARTNERSHIP_ENTRY) as VDP_PARTNERSHIP_ENTRY,
count(VDP_PHONE_ENTRY) as VDP_PHONE_ENTRY,
count(VDP_SEO_ENTRY) as VDP_SEO_ENTRY,
count(VDP_SESSION_CNT) as VDP_SESSION_CNT,
count(VDP_SF_ENTRY) as VDP_SF_ENTRY,
count(VDP_SPOTLIGHT_IMP_FLG) as VDP_SPOTLIGHT_IMP_FLG,
count(VDP_SRP_ENTRY) as VDP_SRP_ENTRY,
count(VDP_TABLET_ENTRY) as VDP_TABLET_ENTRY,
count(VDP_VDP_ENTRY) as VDP_VDP_ENTRY,
count(VDP_VLIST_IMP_FLG) as VDP_VLIST_IMP_FLG,
count(VEHICLE_SKEY) as VEHICLE_SKEY,
count(VEHSEGMENT) as VEHSEGMENT,
count(VIDEO_FLAG) as VIDEO_FLAG,
count(VIN) as VIN,
count(VISITOR_CNT) as VISITOR_CNT,
count(VLIST_IMPRESSION_CNT) as VLIST_IMPRESSION_CNT,
count(VLIST_SESSION_CNT) as VLIST_SESSION_CNT,
count(WEB_VIEW_INV) as WEB_VIEW_INV,
count(ZIP) as ZIP
from &datasource;
run; 
quit;
proc transpose data=t_resp out=t_resp; run;
data t_resp; set t_resp;
rename col1=count;
run;


/**Obtain the numbe of unique values for each variable**/
proc sql;
create table t_resp2 as
select count(distinct ALPHA_IMPRESSION_CNT) as ALPHA_IMPRESSION_CNT,
count(distinct ALPHA_SESSION_CNT) as ALPHA_SESSION_CNT,
count(distinct ATC_DETAIL_PAGE_CNT) as ATC_DETAIL_PAGE_CNT,
count(distinct ATC_IND) as ATC_IND,
count(distinct AVG_COMMENTS_LENGTH) as AVG_COMMENTS_LENGTH,
count(distinct AVG_MSRP) as AVG_MSRP,
count(distinct AVG_PRICE) as AVG_PRICE,
count(distinct AVG_PRICE_TO_MARKET_INDEX) as AVG_PRICE_TO_MARKET_INDEX,
count(distinct AVG_SCARCITY_INDEX) as AVG_SCARCITY_INDEX,
count(distinct BODYSTYLE_NAME) as BODYSTYLE_NAME,
count(distinct BRAND_SEM_IMPRESSION_CNT) as BRAND_SEM_IMPRESSION_CNT,
count(distinct BRAND_SEM_SESSION_CNT) as BRAND_SEM_SESSION_CNT,
count(distinct BUSINESS_ELITE_IND) as BUSINESS_ELITE_IND,
count(distinct CAR_BASE_SRP_IMPRESSION_CNT) as CAR_BASE_SRP_IMPRESSION_CNT,
count(distinct CAR_DETAIL_PAGE_CNT) as CAR_DETAIL_PAGE_CNT,
count(distinct CAR_DURABLE_KEY) as CAR_DURABLE_KEY,
count(distinct CAR_ID) as CAR_ID,
count(distinct CAR_SPOTLIGHT_IMPRESSION_CNT) as CAR_SPOTLIGHT_IMPRESSION_CNT,
count(distinct CAR_SRP_IMPRESSION_CNT) as CAR_SRP_IMPRESSION_CNT,
count(distinct CERTIFIED_IND) as CERTIFIED_IND,
count(distinct CHAT) as CHAT,
count(distinct COMPUTER_IMPRESSION_CNT) as COMPUTER_IMPRESSION_CNT,
count(distinct CREDIT_APP) as CREDIT_APP,
count(distinct CUSTOMER_DURABLE_KEY) as CUSTOMER_DURABLE_KEY,
count(distinct D_NEW_CAR_MERCHANDISING_SCORE) as D_NEW_CAR_MERCHANDISING_SCORE,
count(distinct D_USED_CAR_MERCHANDISING_SCORE) as D_USED_CAR_MERCHANDISING_SCORE,
count(distinct DEALER_MERCHANDISING_SCORE) as DEALER_MERCHANDISING_SCORE,
count(distinct DIRECT_IMPRESSION_CNT) as DIRECT_IMPRESSION_CNT,
count(distinct DIRECT_SESSION_CNT) as DIRECT_SESSION_CNT,
count(distinct DMA) as DMA,
count(distinct DR_MEDIA_IMPRESSION_CNT) as DR_MEDIA_IMPRESSION_CNT,
count(distinct DR_MEDIA_SESSION_CNT) as DR_MEDIA_SESSION_CNT,
count(distinct EMAILS) as EMAILS,
count(distinct FRONT_LINE_LISTING_IND) as FRONT_LINE_LISTING_IND,
count(distinct FRONT_LINE_PRO_IND) as FRONT_LINE_PRO_IND,
count(distinct HP_IMPRESSION_CNT) as HP_IMPRESSION_CNT,
count(distinct HP_SESSION_CNT) as HP_SESSION_CNT,
count(distinct IMAGE_FLG) as IMAGE_FLG,
count(distinct INCENTIVE_PRICE) as INCENTIVE_PRICE,
count(distinct INCENTIVE_PRICE_IND) as INCENTIVE_PRICE_IND,
count(distinct INTEREST_EVENTS_1) as INTEREST_EVENTS_1,
count(distinct INTEREST_EVENTS_2) as INTEREST_EVENTS_2,
count(distinct KBB_IND) as KBB_IND,
count(distinct KBB_PHOTO_FLG) as KBB_PHOTO_FLG,
count(distinct LEAD_1) as LEAD_1,
count(distinct LEAD_2) as LEAD_2,
count(distinct LISTING_COMMENTS_IND) as LISTING_COMMENTS_IND,
count(distinct LISTING_DURABLE_KEY) as LISTING_DURABLE_KEY,
count(distinct LISTING_TYPE) as LISTING_TYPE,
count(distinct MAKE_NAME) as MAKE_NAME,
count(distinct MAP) as MAP,
count(distinct MAX_DAYS_ON_SITE) as MAX_DAYS_ON_SITE,
count(distinct MAX_MILEAGE) as MAX_MILEAGE,
count(distinct MOBILE_FYC_DETAIL_PAGE_CNT) as MOBILE_FYC_DETAIL_PAGE_CNT,
count(distinct MOBILE_FYC_SRP_IMPRESSION_CNT) as MOBILE_FYC_SRP_IMPRESSION_CNT,
count(distinct MODEL_NAME) as MODEL_NAME,
count(distinct MODEL_YEAR) as MODEL_YEAR,
count(distinct NEW_IND) as NEW_IND,
count(distinct NON_BRAND_SEM_IMPRESSION_CNT) as NON_BRAND_SEM_IMPRESSION_CNT,
count(distinct NON_BRAND_SEM_SESSION_CNT) as NON_BRAND_SEM_SESSION_CNT,
count(distinct OTHER_EP_IMPRESSION_CNT) as OTHER_EP_IMPRESSION_CNT,
count(distinct OTHER_EP_SESSION_CNT) as OTHER_EP_SESSION_CNT,
count(distinct OTHER_SOT_IMPRESSION_CNT) as OTHER_SOT_IMPRESSION_CNT,
count(distinct OTHER_SOT_SESSION_CNT) as OTHER_SOT_SESSION_CNT,
count(distinct OTHERLSTG_IMPRESSION_CNT) as OTHERLSTG_IMPRESSION_CNT,
count(distinct OTHERLSTG_SESSION_CNT) as OTHERLSTG_SESSION_CNT,
count(distinct OWNER_ID) as OWNER_ID,
count(distinct PARTNERSHIP_IMPRESSION_CNT) as PARTNERSHIP_IMPRESSION_CNT,
count(distinct PARTNERSHIP_SESSION_CNT) as PARTNERSHIP_SESSION_CNT,
count(distinct PAYMENT_OFFERS_IND) as PAYMENT_OFFERS_IND,
count(distinct PAYMENT_ON_LISTING_IND) as PAYMENT_ON_LISTING_IND,
count(distinct PHONE_IMPRESSION_CNT) as PHONE_IMPRESSION_CNT,
count(distinct PHONE_LOOKUP) as PHONE_LOOKUP,
count(distinct POTENTIAL_SALE) as POTENTIAL_SALE,
count(distinct PRINT) as PRINT,
count(distinct PRIVATE_SELLER_FLAG) as PRIVATE_SELLER_FLAG,
count(distinct RN) as RN,
count(distinct SAVES) as SAVES,
count(distinct SEO_IMPRESSION_CNT) as SEO_IMPRESSION_CNT,
count(distinct SEO_SESSION_CNT) as SEO_SESSION_CNT,
count(distinct SESSION_CNT) as SESSION_CNT,
count(distinct SF_IMPRESSION_CNT) as SF_IMPRESSION_CNT,
count(distinct SF_SESSION_CNT) as SF_SESSION_CNT,
count(distinct SPIN360_FLAG) as SPIN360_FLAG,
count(distinct SPOTLIGHT_IMPRESSION_CNT) as SPOTLIGHT_IMPRESSION_CNT,
count(distinct SPOTLIGHT_IND) as SPOTLIGHT_IND,
count(distinct SPOTLIGHT_SESSION_CNT) as SPOTLIGHT_SESSION_CNT,
count(distinct SRP_ALP_IMPRESSION_FLG) as SRP_ALP_IMPRESSION_FLG,
count(distinct SRP_ALPHA_IMPRESSION_CNT) as SRP_ALPHA_IMPRESSION_CNT,
count(distinct SRP_ALPHA_SESSION_CNT) as SRP_ALPHA_SESSION_CNT,
count(distinct SRP_IMPRESSION_CNT) as SRP_IMPRESSION_CNT,
count(distinct SRP_OTH_IMPRESSION_FLG) as SRP_OTH_IMPRESSION_FLG,
count(distinct SRP_OTHERLSTG_IMPRESSION_CNT) as SRP_OTHERLSTG_IMPRESSION_CNT,
count(distinct SRP_OTHERLSTG_SESSION_CNT) as SRP_OTHERLSTG_SESSION_CNT,
count(distinct SRP_SESSION_CNT) as SRP_SESSION_CNT,
count(distinct SRP_SP_IMPRESSION_FLG) as SRP_SP_IMPRESSION_FLG,
count(distinct SRP_SPOTLIGHT_IMPRESSION_CNT) as SRP_SPOTLIGHT_IMPRESSION_CNT,
count(distinct SRP_SPOTLIGHT_SESSION_CNT) as SRP_SPOTLIGHT_SESSION_CNT,
count(distinct SRP_VLIST_IMPRESSION_CNT) as SRP_VLIST_IMPRESSION_CNT,
count(distinct SRP_VLIST_IMPRESSION_FLG) as SRP_VLIST_IMPRESSION_FLG,
count(distinct SRP_VLIST_SESSION_CNT) as SRP_VLIST_SESSION_CNT,
count(distinct TABLET_IMPRESSION_CNT) as TABLET_IMPRESSION_CNT,
count(distinct TOTAL_IMP) as TOTAL_IMP,
count(distinct TOTAL_SRPI) as TOTAL_SRPI,
count(distinct VARIANCE_BUCKET) as VARIANCE_BUCKET,
count(distinct VDP) as VDP,
count(distinct VDP_ALPHA_IMP_FLG) as VDP_ALPHA_IMP_FLG,
count(distinct VDP_BRAND_SEM_ENTRY) as VDP_BRAND_SEM_ENTRY,
count(distinct VDP_COMPUTER_ENTRY) as VDP_COMPUTER_ENTRY,
count(distinct VDP_DIRECT_ENTRY) as VDP_DIRECT_ENTRY,
count(distinct VDP_DR_MEDIA_ENTRY) as VDP_DR_MEDIA_ENTRY,
count(distinct VDP_HP_ENTRY) as VDP_HP_ENTRY,
count(distinct VDP_IMPRESSION_CNT) as VDP_IMPRESSION_CNT,
count(distinct VDP_NON_BRAND_SEM_ENTRY) as VDP_NON_BRAND_SEM_ENTRY,
count(distinct VDP_OTHER_EP_ENTRY) as VDP_OTHER_EP_ENTRY,
count(distinct VDP_OTHER_SOT_ENTRY) as VDP_OTHER_SOT_ENTRY,
count(distinct VDP_OTHERLSTG_IMP_FLG) as VDP_OTHERLSTG_IMP_FLG,
count(distinct VDP_PARTNERSHIP_ENTRY) as VDP_PARTNERSHIP_ENTRY,
count(distinct VDP_PHONE_ENTRY) as VDP_PHONE_ENTRY,
count(distinct VDP_SEO_ENTRY) as VDP_SEO_ENTRY,
count(distinct VDP_SESSION_CNT) as VDP_SESSION_CNT,
count(distinct VDP_SF_ENTRY) as VDP_SF_ENTRY,
count(distinct VDP_SPOTLIGHT_IMP_FLG) as VDP_SPOTLIGHT_IMP_FLG,
count(distinct VDP_SRP_ENTRY) as VDP_SRP_ENTRY,
count(distinct VDP_TABLET_ENTRY) as VDP_TABLET_ENTRY,
count(distinct VDP_VDP_ENTRY) as VDP_VDP_ENTRY,
count(distinct VDP_VLIST_IMP_FLG) as VDP_VLIST_IMP_FLG,
count(distinct VEHICLE_SKEY) as VEHICLE_SKEY,
count(distinct VEHSEGMENT) as VEHSEGMENT,
count(distinct VIDEO_FLAG) as VIDEO_FLAG,
count(distinct VIN) as VIN,
count(distinct VISITOR_CNT) as VISITOR_CNT,
count(distinct VLIST_IMPRESSION_CNT) as VLIST_IMPRESSION_CNT,
count(distinct VLIST_SESSION_CNT) as VLIST_SESSION_CNT,
count(distinct WEB_VIEW_INV) as WEB_VIEW_INV,
count(distinct ZIP) as ZIP
from &datasource;
run; 
quit;
proc transpose data=t_resp2 out=t_resp2; run;
data t_resp2; set t_resp2;
rename col1=unique_values;
run;


/**Put number of variables, counts and unique values in one table**/
proc sql;
create table t_resp3 as
select *
from datavars, t_resp, t_resp2 
where datavars.name=t_resp._name_ and t_resp._name_=t_resp2._name_;
run;
quit;
data t_resp3; set t_resp3;
keep NAME	TYPE	LENGTH	VARNUM	LABEL	FORMAT	FORMATL	INFORMAT	INFORML	NOBS	_NAME_	count	unique_values
;
run;
proc print data=t_resp3 noobs; run;




/**variables for Frequencies**/
%let varsforfreqs=ATC_DETAIL_PAGE_CNT
BUSINESS_ELITE_IND
CERTIFIED_IND
CHAT
LISTING_TYPE
NEW_IND
PAYMENT_OFFERS_IND
PHONE_LOOKUP
PRIVATE_SELLER_FLAG
RN
SEO_IMPRESSION_CNT
VDP_SEO_ENTRY
ATC_IND
CREDIT_APP
FRONT_LINE_LISTING_IND
FRONT_LINE_PRO_IND
IMAGE_FLG
INCENTIVE_PRICE_IND
KBB_IND
LISTING_COMMENTS_IND
PAYMENT_ON_LISTING_IND
POTENTIAL_SALE
SPIN360_FLAG
SPOTLIGHT_IND
SRP_ALP_IMPRESSION_FLG
SRP_OTH_IMPRESSION_FLG
SRP_SP_IMPRESSION_FLG
SRP_VLIST_IMPRESSION_FLG
VDP_ALPHA_IMP_FLG
VDP_BRAND_SEM_ENTRY
VDP_COMPUTER_ENTRY
VDP_DIRECT_ENTRY
VDP_DR_MEDIA_ENTRY
VDP_HP_ENTRY
VDP_NON_BRAND_SEM_ENTRY
VDP_OTHER_EP_ENTRY
VDP_OTHER_SOT_ENTRY
VDP_OTHERLSTG_IMP_FLG
VDP_PARTNERSHIP_ENTRY
VDP_PHONE_ENTRY
VDP_SF_ENTRY
VDP_SPOTLIGHT_IMP_FLG
VDP_SRP_ENTRY
VDP_TABLET_ENTRY
VDP_VDP_ENTRY
VDP_VLIST_IMP_FLG
VIDEO_FLAG
VARIANCE_BUCKET
MODEL_YEAR
PRINT
SRP_OTHERLSTG_SESSION_CNT
BODYSTYLE_NAME
SPOTLIGHT_SESSION_CNT
ALPHA_SESSION_CNT
MAP
SRP_OTHERLSTG_IMPRESSION_CNT
ALPHA_IMPRESSION_CNT
SPOTLIGHT_IMPRESSION_CNT
VEHSEGMENT
DR_MEDIA_SESSION_CNT
PARTNERSHIP_SESSION_CNT
EMAILS
LEAD_1
LEAD_2
DR_MEDIA_IMPRESSION_CNT
PARTNERSHIP_IMPRESSION_CNT
OTHER_EP_IMPRESSION_CNT
OTHER_EP_SESSION_CNT
WEB_VIEW_INV
OTHER_SOT_SESSION_CNT
MAKE_NAME
SF_SESSION_CNT
OTHER_SOT_IMPRESSION_CNT
SAVES
INTEREST_EVENTS_1
SF_IMPRESSION_CNT
VLIST_IMPRESSION_CNT
VLIST_SESSION_CNT
INTEREST_EVENTS_2
BRAND_SEM_SESSION_CNT
D_NEW_CAR_MERCHANDISING_SCORE
DEALER_MERCHANDISING_SCORE
D_USED_CAR_MERCHANDISING_SCORE
BRAND_SEM_IMPRESSION_CNT
VDP_SESSION_CNT
TABLET_IMPRESSION_CNT
VDP_IMPRESSION_CNT
NON_BRAND_SEM_SESSION_CNT
SEO_SESSION_CNT
NON_BRAND_SEM_IMPRESSION_CNT
DMA
PHONE_IMPRESSION_CNT
SRP_SESSION_CNT
HP_SESSION_CNT
SRP_IMPRESSION_CNT
DIRECT_SESSION_CNT
VISITOR_CNT
SESSION_CNT
HP_IMPRESSION_CNT
DIRECT_IMPRESSION_CNT
MAX_DAYS_ON_SITE
OTHERLSTG_SESSION_CNT
COMPUTER_IMPRESSION_CNT
TOTAL_IMP
CAR_DETAIL_PAGE_CNT
OTHERLSTG_IMPRESSION_CNT
MODEL_NAME
MOBILE_FYC_DETAIL_PAGE_CNT
SRP_ALPHA_SESSION_CNT
VDP

;


/**variables for Means Analysis**/
%let varsformeans=ATC_DETAIL_PAGE_CNT
BUSINESS_ELITE_IND
CERTIFIED_IND
CHAT
NEW_IND
PAYMENT_OFFERS_IND
PHONE_LOOKUP
PRIVATE_SELLER_FLAG
RN
SEO_IMPRESSION_CNT
VDP_SEO_ENTRY
ATC_IND
CREDIT_APP
FRONT_LINE_LISTING_IND
FRONT_LINE_PRO_IND
IMAGE_FLG
INCENTIVE_PRICE_IND
KBB_IND
LISTING_COMMENTS_IND
PAYMENT_ON_LISTING_IND
POTENTIAL_SALE
SPIN360_FLAG
SPOTLIGHT_IND
SRP_ALP_IMPRESSION_FLG
SRP_OTH_IMPRESSION_FLG
SRP_SP_IMPRESSION_FLG
SRP_VLIST_IMPRESSION_FLG
VDP_ALPHA_IMP_FLG
VDP_BRAND_SEM_ENTRY
VDP_COMPUTER_ENTRY
VDP_DIRECT_ENTRY
VDP_DR_MEDIA_ENTRY
VDP_HP_ENTRY
VDP_NON_BRAND_SEM_ENTRY
VDP_OTHER_EP_ENTRY
VDP_OTHER_SOT_ENTRY
VDP_OTHERLSTG_IMP_FLG
VDP_PARTNERSHIP_ENTRY
VDP_PHONE_ENTRY
VDP_SF_ENTRY
VDP_SPOTLIGHT_IMP_FLG
VDP_SRP_ENTRY
VDP_TABLET_ENTRY
VDP_VDP_ENTRY
VDP_VLIST_IMP_FLG
VIDEO_FLAG
PRINT
SRP_OTHERLSTG_SESSION_CNT
SPOTLIGHT_SESSION_CNT
ALPHA_SESSION_CNT
MAP
SRP_OTHERLSTG_IMPRESSION_CNT
ALPHA_IMPRESSION_CNT
SPOTLIGHT_IMPRESSION_CNT
DR_MEDIA_SESSION_CNT
PARTNERSHIP_SESSION_CNT
EMAILS
LEAD_1
LEAD_2
DR_MEDIA_IMPRESSION_CNT
PARTNERSHIP_IMPRESSION_CNT
OTHER_EP_IMPRESSION_CNT
OTHER_EP_SESSION_CNT
WEB_VIEW_INV
OTHER_SOT_SESSION_CNT
SF_SESSION_CNT
OTHER_SOT_IMPRESSION_CNT
SAVES
INTEREST_EVENTS_1
SF_IMPRESSION_CNT
VLIST_IMPRESSION_CNT
VLIST_SESSION_CNT
INTEREST_EVENTS_2
BRAND_SEM_SESSION_CNT
D_NEW_CAR_MERCHANDISING_SCORE
DEALER_MERCHANDISING_SCORE
D_USED_CAR_MERCHANDISING_SCORE
BRAND_SEM_IMPRESSION_CNT
VDP_SESSION_CNT
TABLET_IMPRESSION_CNT
VDP_IMPRESSION_CNT
NON_BRAND_SEM_SESSION_CNT
SEO_SESSION_CNT
NON_BRAND_SEM_IMPRESSION_CNT
PHONE_IMPRESSION_CNT
SRP_SESSION_CNT
HP_SESSION_CNT
SRP_IMPRESSION_CNT
DIRECT_SESSION_CNT
VISITOR_CNT
SESSION_CNT
HP_IMPRESSION_CNT
DIRECT_IMPRESSION_CNT
MAX_DAYS_ON_SITE
OTHERLSTG_SESSION_CNT
COMPUTER_IMPRESSION_CNT
TOTAL_IMP
CAR_DETAIL_PAGE_CNT
OTHERLSTG_IMPRESSION_CNT
MOBILE_FYC_DETAIL_PAGE_CNT
SRP_ALPHA_SESSION_CNT
VDP
SRP_SPOTLIGHT_SESSION_CNT
SRP_ALPHA_IMPRESSION_CNT
CAR_SPOTLIGHT_IMPRESSION_CNT
SRP_SPOTLIGHT_IMPRESSION_CNT
ZIP
SRP_VLIST_SESSION_CNT
VEHICLE_SKEY
MOBILE_FYC_SRP_IMPRESSION_CNT
MAX_MILEAGE
SRP_VLIST_IMPRESSION_CNT
CAR_SRP_IMPRESSION_CNT
CUSTOMER_DURABLE_KEY
OWNER_ID
CAR_BASE_SRP_IMPRESSION_CNT
TOTAL_SRPI
KBB_PHOTO_FLG
INCENTIVE_PRICE
AVG_MSRP
AVG_SCARCITY_INDEX
AVG_PRICE_TO_MARKET_INDEX
AVG_COMMENTS_LENGTH
AVG_PRICE
CAR_DURABLE_KEY
CAR_ID
LISTING_DURABLE_KEY
;



proc freq data=&datasource;
tables lead_1*lead_2;
run;

proc freq data=&datasource;
tables &varsforfreqs;
run;

proc univariate data=&datasource;
var &varsformeans;
run;

proc corr data=&datasource;
var &varsformeans;
run;


proc means data=&datasource n sum mean median mode min max std clm;
class lead_1;
var &varsformeans;
run;

proc means data=&datasource n sum mean median mode min max std clm;
class lead_2;
var &varsformeans;
run;




/**create dummies for leads**/
data data_file; set &datasource;
resp_id=LISTING_DURABLE_KEY;

if lead_1 ge 1 then lead_1_dum=1; else lead_1_dum=0;
if lead_2 ge 1 then lead_2_dum=1; else lead_2_dum=0;

if VARIANCE_BUCKET eq 'Above FMR' then VARIANCE_BUCKET1=1; else VARIANCE_BUCKET1=0;
if VARIANCE_BUCKET eq 'Below FMR' then VARIANCE_BUCKET2=1; else VARIANCE_BUCKET2=0;
if VARIANCE_BUCKET eq 'NULL' then VARIANCE_BUCKET3=1; else VARIANCE_BUCKET3=0;
if VARIANCE_BUCKET eq 'Null Listing Price' then VARIANCE_BUCKET4=1; else VARIANCE_BUCKET4=0;
if VARIANCE_BUCKET eq 'Within FMR' then VARIANCE_BUCKET5=1; else VARIANCE_BUCKET5=0;

if MODEL_YEAR eq '2014' then MODEL_YEAR1=1; else MODEL_YEAR1=0;
if MODEL_YEAR eq '2015' then MODEL_YEAR2=1; else MODEL_YEAR2=0;
if MODEL_YEAR eq '2016' then MODEL_YEAR3=1; else MODEL_YEAR3=0;
if MODEL_YEAR eq '2017' then MODEL_YEAR4=1; else MODEL_YEAR4=0;
if MODEL_YEAR eq '2018' then MODEL_YEAR5=1; else MODEL_YEAR5=0;
if MODEL_YEAR eq '2019' then MODEL_YEAR6=1; else MODEL_YEAR6=0;
if MODEL_YEAR eq 'NULL' then MODEL_YEAR7=1; else MODEL_YEAR7=0;

if BODYSTYLE_NAME eq 'Convertible' then BODYSTYLE_NAME1=1; else BODYSTYLE_NAME1=0;
if BODYSTYLE_NAME eq 'Coupe' then BODYSTYLE_NAME2=1; else BODYSTYLE_NAME2=0;
if BODYSTYLE_NAME eq 'Hatchback' then BODYSTYLE_NAME3=1; else BODYSTYLE_NAME3=0;
if BODYSTYLE_NAME eq 'Sedan' then BODYSTYLE_NAME4=1; else BODYSTYLE_NAME4=0;
if BODYSTYLE_NAME eq 'Sport Utility' then BODYSTYLE_NAME5=1; else BODYSTYLE_NAME5=0;
if BODYSTYLE_NAME eq 'Truck' then BODYSTYLE_NAME6=1; else BODYSTYLE_NAME6=0;
if BODYSTYLE_NAME eq 'Van' then BODYSTYLE_NAME7=1; else BODYSTYLE_NAME7=0;
if BODYSTYLE_NAME eq 'Wagon' then BODYSTYLE_NAME8=1; else BODYSTYLE_NAME8=0;

if VEHSEGMENT eq 'Compact' then VEHSEGMENT1=1; else VEHSEGMENT1=0;
if VEHSEGMENT eq 'Compact Sport Utility' then VEHSEGMENT2=1; else VEHSEGMENT2=0;
if VEHSEGMENT eq 'Full Size Vans' then VEHSEGMENT3=1; else VEHSEGMENT3=0;
if VEHSEGMENT eq 'Intermediate' then VEHSEGMENT4=1; else VEHSEGMENT4=0;
if VEHSEGMENT eq 'Intermediate Sport Utility' then VEHSEGMENT5=1; else VEHSEGMENT5=0;
if VEHSEGMENT eq 'Large Pick-up' then VEHSEGMENT6=1; else VEHSEGMENT6=0;
if VEHSEGMENT eq 'Large Sport Utility' then VEHSEGMENT7=1; else VEHSEGMENT7=0;
if VEHSEGMENT eq 'Luxury' then VEHSEGMENT8=1; else VEHSEGMENT8=0;
if VEHSEGMENT eq 'Luxury High' then VEHSEGMENT9=1; else VEHSEGMENT9=0;
if VEHSEGMENT eq 'Luxury Sport' then VEHSEGMENT10=1; else VEHSEGMENT10=0;
if VEHSEGMENT eq 'Luxury Sport Utility' then VEHSEGMENT11=1; else VEHSEGMENT11=0;
if VEHSEGMENT eq 'NULL' then VEHSEGMENT12=1; else VEHSEGMENT12=0;
if VEHSEGMENT eq 'Small Pick-up' then VEHSEGMENT13=1; else VEHSEGMENT13=0;
if VEHSEGMENT eq 'Small Van' then VEHSEGMENT14=1; else VEHSEGMENT14=0;
if VEHSEGMENT eq 'Sport' then VEHSEGMENT15=1; else VEHSEGMENT15=0;
if VEHSEGMENT eq 'Subcompact' then VEHSEGMENT16=1; else VEHSEGMENT16=0;

if MAKE_NAME eq 'Acura' then MAKE_NAME1=1; else MAKE_NAME1=0;
if MAKE_NAME eq 'Alfa Romeo' then MAKE_NAME2=1; else MAKE_NAME2=0;
if MAKE_NAME eq 'Aston Martin' then MAKE_NAME3=1; else MAKE_NAME3=0;
if MAKE_NAME eq 'Audi' then MAKE_NAME4=1; else MAKE_NAME4=0;
if MAKE_NAME eq 'BMW' then MAKE_NAME5=1; else MAKE_NAME5=0;
if MAKE_NAME eq 'Bentley' then MAKE_NAME6=1; else MAKE_NAME6=0;
if MAKE_NAME eq 'Buick' then MAKE_NAME7=1; else MAKE_NAME7=0;
if MAKE_NAME eq 'Cadillac' then MAKE_NAME8=1; else MAKE_NAME8=0;
if MAKE_NAME eq 'Chevrolet' then MAKE_NAME9=1; else MAKE_NAME9=0;
if MAKE_NAME eq 'Chrysler' then MAKE_NAME10=1; else MAKE_NAME10=0;
if MAKE_NAME eq 'Dodge' then MAKE_NAME11=1; else MAKE_NAME11=0;
if MAKE_NAME eq 'Ferrari' then MAKE_NAME12=1; else MAKE_NAME12=0;
if MAKE_NAME eq 'Fiat' then MAKE_NAME13=1; else MAKE_NAME13=0;
if MAKE_NAME eq 'Ford' then MAKE_NAME14=1; else MAKE_NAME14=0;
if MAKE_NAME eq 'GMC' then MAKE_NAME15=1; else MAKE_NAME15=0;
if MAKE_NAME eq 'Genesis' then MAKE_NAME16=1; else MAKE_NAME16=0;
if MAKE_NAME eq 'Honda' then MAKE_NAME17=1; else MAKE_NAME17=0;
if MAKE_NAME eq 'Hyundai' then MAKE_NAME18=1; else MAKE_NAME18=0;
if MAKE_NAME eq 'INFINITI' then MAKE_NAME19=1; else MAKE_NAME19=0;
if MAKE_NAME eq 'Jaguar' then MAKE_NAME20=1; else MAKE_NAME20=0;
if MAKE_NAME eq 'Jeep' then MAKE_NAME21=1; else MAKE_NAME21=0;
if MAKE_NAME eq 'Kia' then MAKE_NAME22=1; else MAKE_NAME22=0;
if MAKE_NAME eq 'Lamborghini' then MAKE_NAME23=1; else MAKE_NAME23=0;
if MAKE_NAME eq 'Land Rover' then MAKE_NAME24=1; else MAKE_NAME24=0;
if MAKE_NAME eq 'Lexus' then MAKE_NAME25=1; else MAKE_NAME25=0;
if MAKE_NAME eq 'Lincoln' then MAKE_NAME26=1; else MAKE_NAME26=0;
if MAKE_NAME eq 'Lotus' then MAKE_NAME27=1; else MAKE_NAME27=0;
if MAKE_NAME eq 'MINI' then MAKE_NAME28=1; else MAKE_NAME28=0;
if MAKE_NAME eq 'Maserati' then MAKE_NAME29=1; else MAKE_NAME29=0;
if MAKE_NAME eq 'Mazda' then MAKE_NAME30=1; else MAKE_NAME30=0;
if MAKE_NAME eq 'McLaren' then MAKE_NAME31=1; else MAKE_NAME31=0;
if MAKE_NAME eq 'Mercedes-Benz' then MAKE_NAME32=1; else MAKE_NAME32=0;
if MAKE_NAME eq 'Mitsubishi' then MAKE_NAME33=1; else MAKE_NAME33=0;
if MAKE_NAME eq 'Nissan' then MAKE_NAME34=1; else MAKE_NAME34=0;
if MAKE_NAME eq 'Porsche' then MAKE_NAME35=1; else MAKE_NAME35=0;
if MAKE_NAME eq 'RAM' then MAKE_NAME36=1; else MAKE_NAME36=0;
if MAKE_NAME eq 'Rolls-Royce' then MAKE_NAME37=1; else MAKE_NAME37=0;
if MAKE_NAME eq 'Scion' then MAKE_NAME38=1; else MAKE_NAME38=0;
if MAKE_NAME eq 'Subaru' then MAKE_NAME39=1; else MAKE_NAME39=0;
if MAKE_NAME eq 'Toyota' then MAKE_NAME40=1; else MAKE_NAME40=0;
if MAKE_NAME eq 'Volkswagen' then MAKE_NAME41=1; else MAKE_NAME41=0;
if MAKE_NAME eq 'Volvo' then MAKE_NAME42=1; else MAKE_NAME42=0;
if MAKE_NAME eq 'smart' then MAKE_NAME43=1; else MAKE_NAME43=0;


label VARIANCE_BUCKET1='VARIANCE_BUCKET: Above FMR'
VARIANCE_BUCKET2='VARIANCE_BUCKET: Below FMR'
VARIANCE_BUCKET3='VARIANCE_BUCKET: NULL'
VARIANCE_BUCKET4='VARIANCE_BUCKET: Null Listing Price'
VARIANCE_BUCKET5='VARIANCE_BUCKET: Within FMR'

MODEL_YEAR1='MODEL_YEAR: 2014'
MODEL_YEAR2='MODEL_YEAR: 2015'
MODEL_YEAR3='MODEL_YEAR: 2016'
MODEL_YEAR4='MODEL_YEAR: 2017'
MODEL_YEAR5='MODEL_YEAR: 2018'
MODEL_YEAR6='MODEL_YEAR: 2019'
MODEL_YEAR7='MODEL_YEAR: NULL'

BODYSTYLE_NAME1='BODYSTYLE_NAME: Convertible'
BODYSTYLE_NAME2='BODYSTYLE_NAME: Coupe'
BODYSTYLE_NAME3='BODYSTYLE_NAME: Hatchback'
BODYSTYLE_NAME4='BODYSTYLE_NAME: Sedan'
BODYSTYLE_NAME5='BODYSTYLE_NAME: Sport Utility'
BODYSTYLE_NAME6='BODYSTYLE_NAME: Truck'
BODYSTYLE_NAME7='BODYSTYLE_NAME: Van'
BODYSTYLE_NAME8='BODYSTYLE_NAME: Wagon'

VEHSEGMENT1='VEHSEGMENT: Compact'
VEHSEGMENT2='VEHSEGMENT: Compact Sport Utility'
VEHSEGMENT3='VEHSEGMENT: Full Size Vans'
VEHSEGMENT4='VEHSEGMENT: Intermediate'
VEHSEGMENT5='VEHSEGMENT: Intermediate Sport Utility'
VEHSEGMENT6='VEHSEGMENT: Large Pick-up'
VEHSEGMENT7='VEHSEGMENT: Large Sport Utility'
VEHSEGMENT8='VEHSEGMENT: Luxury'
VEHSEGMENT9='VEHSEGMENT: Luxury High'
VEHSEGMENT10='VEHSEGMENT: Luxury Sport'
VEHSEGMENT11='VEHSEGMENT: Luxury Sport Utility'
VEHSEGMENT12='VEHSEGMENT: NULL'
VEHSEGMENT13='VEHSEGMENT: Small Pick-up'
VEHSEGMENT14='VEHSEGMENT: Small Van'
VEHSEGMENT15='VEHSEGMENT: Sport'
VEHSEGMENT16='VEHSEGMENT: Subcompact'

MAKE_NAME1='MAKE_NAME: Acura'
MAKE_NAME2='MAKE_NAME: Alfa Romeo'
MAKE_NAME3='MAKE_NAME: Aston Martin'
MAKE_NAME4='MAKE_NAME: Audi'
MAKE_NAME5='MAKE_NAME: BMW'
MAKE_NAME6='MAKE_NAME: Bentley'
MAKE_NAME7='MAKE_NAME: Buick'
MAKE_NAME8='MAKE_NAME: Cadillac'
MAKE_NAME9='MAKE_NAME: Chevrolet'
MAKE_NAME10='MAKE_NAME: Chrysler'
MAKE_NAME11='MAKE_NAME: Dodge'
MAKE_NAME12='MAKE_NAME: Ferrari'
MAKE_NAME13='MAKE_NAME: Fiat'
MAKE_NAME14='MAKE_NAME: Ford'
MAKE_NAME15='MAKE_NAME: GMC'
MAKE_NAME16='MAKE_NAME: Genesis'
MAKE_NAME17='MAKE_NAME: Honda'
MAKE_NAME18='MAKE_NAME: Hyundai'
MAKE_NAME19='MAKE_NAME: INFINITI'
MAKE_NAME20='MAKE_NAME: Jaguar'
MAKE_NAME21='MAKE_NAME: Jeep'
MAKE_NAME22='MAKE_NAME: Kia'
MAKE_NAME23='MAKE_NAME: Lamborghini'
MAKE_NAME24='MAKE_NAME: Land Rover'
MAKE_NAME25='MAKE_NAME: Lexus'
MAKE_NAME26='MAKE_NAME: Lincoln'
MAKE_NAME27='MAKE_NAME: Lotus'
MAKE_NAME28='MAKE_NAME: MINI'
MAKE_NAME29='MAKE_NAME: Maserati'
MAKE_NAME30='MAKE_NAME: Mazda'
MAKE_NAME31='MAKE_NAME: McLaren'
MAKE_NAME32='MAKE_NAME: Mercedes-Benz'
MAKE_NAME33='MAKE_NAME: Mitsubishi'
MAKE_NAME34='MAKE_NAME: Nissan'
MAKE_NAME35='MAKE_NAME: Porsche'
MAKE_NAME36='MAKE_NAME: RAM'
MAKE_NAME37='MAKE_NAME: Rolls-Royce'
MAKE_NAME38='MAKE_NAME: Scion'
MAKE_NAME39='MAKE_NAME: Subaru'
MAKE_NAME40='MAKE_NAME: Toyota'
MAKE_NAME41='MAKE_NAME: Volkswagen'
MAKE_NAME42='MAKE_NAME: Volvo'
MAKE_NAME43='MAKE_NAME: smart'


ATC_DETAIL_PAGE_CNT='ATC_DETAIL_PAGE_CNT'
BUSINESS_ELITE_IND='BUSINESS_ELITE_IND'
CERTIFIED_IND='CERTIFIED_IND'
CHAT='CHAT'
LISTING_TYPE='LISTING_TYPE'
NEW_IND='NEW_IND'
PAYMENT_OFFERS_IND='PAYMENT_OFFERS_IND'
PHONE_LOOKUP='PHONE_LOOKUP'
PRIVATE_SELLER_FLAG='PRIVATE_SELLER_FLAG'
RN='RN'
SEO_IMPRESSION_CNT='SEO_IMPRESSION_CNT'
VDP_SEO_ENTRY='VDP_SEO_ENTRY'
ATC_IND='ATC_IND'
CREDIT_APP='CREDIT_APP'
FRONT_LINE_LISTING_IND='FRONT_LINE_LISTING_IND'
FRONT_LINE_PRO_IND='FRONT_LINE_PRO_IND'
IMAGE_FLG='IMAGE_FLG'
INCENTIVE_PRICE_IND='INCENTIVE_PRICE_IND'
KBB_IND='KBB_IND'
LISTING_COMMENTS_IND='LISTING_COMMENTS_IND'
PAYMENT_ON_LISTING_IND='PAYMENT_ON_LISTING_IND'
POTENTIAL_SALE='POTENTIAL_SALE'
SPIN360_FLAG='SPIN360_FLAG'
SPOTLIGHT_IND='SPOTLIGHT_IND'
SRP_ALP_IMPRESSION_FLG='SRP_ALP_IMPRESSION_FLG'
SRP_OTH_IMPRESSION_FLG='SRP_OTH_IMPRESSION_FLG'
SRP_SP_IMPRESSION_FLG='SRP_SP_IMPRESSION_FLG'
SRP_VLIST_IMPRESSION_FLG='SRP_VLIST_IMPRESSION_FLG'
VDP_ALPHA_IMP_FLG='VDP_ALPHA_IMP_FLG'
VDP_BRAND_SEM_ENTRY='VDP_BRAND_SEM_ENTRY'
VDP_COMPUTER_ENTRY='VDP_COMPUTER_ENTRY'
VDP_DIRECT_ENTRY='VDP_DIRECT_ENTRY'
VDP_DR_MEDIA_ENTRY='VDP_DR_MEDIA_ENTRY'
VDP_HP_ENTRY='VDP_HP_ENTRY'
VDP_NON_BRAND_SEM_ENTRY='VDP_NON_BRAND_SEM_ENTRY'
VDP_OTHER_EP_ENTRY='VDP_OTHER_EP_ENTRY'
VDP_OTHER_SOT_ENTRY='VDP_OTHER_SOT_ENTRY'
VDP_OTHERLSTG_IMP_FLG='VDP_OTHERLSTG_IMP_FLG'
VDP_PARTNERSHIP_ENTRY='VDP_PARTNERSHIP_ENTRY'
VDP_PHONE_ENTRY='VDP_PHONE_ENTRY'
VDP_SF_ENTRY='VDP_SF_ENTRY'
VDP_SPOTLIGHT_IMP_FLG='VDP_SPOTLIGHT_IMP_FLG'
VDP_SRP_ENTRY='VDP_SRP_ENTRY'
VDP_TABLET_ENTRY='VDP_TABLET_ENTRY'
VDP_VDP_ENTRY='VDP_VDP_ENTRY'
VDP_VLIST_IMP_FLG='VDP_VLIST_IMP_FLG'
VIDEO_FLAG='VIDEO_FLAG'
VARIANCE_BUCKET='VARIANCE_BUCKET'
MODEL_YEAR='MODEL_YEAR'
PRINT='PRINT'
SRP_OTHERLSTG_SESSION_CNT='SRP_OTHERLSTG_SESSION_CNT'
BODYSTYLE_NAME='BODYSTYLE_NAME'
SPOTLIGHT_SESSION_CNT='SPOTLIGHT_SESSION_CNT'
ALPHA_SESSION_CNT='ALPHA_SESSION_CNT'
MAP='MAP'
SRP_OTHERLSTG_IMPRESSION_CNT='SRP_OTHERLSTG_IMPRESSION_CNT'
ALPHA_IMPRESSION_CNT='ALPHA_IMPRESSION_CNT'
SPOTLIGHT_IMPRESSION_CNT='SPOTLIGHT_IMPRESSION_CNT'
VEHSEGMENT='VEHSEGMENT'
DR_MEDIA_SESSION_CNT='DR_MEDIA_SESSION_CNT'
PARTNERSHIP_SESSION_CNT='PARTNERSHIP_SESSION_CNT'
EMAILS='EMAILS'
LEAD_1='LEAD_1'
LEAD_2='LEAD_2'
DR_MEDIA_IMPRESSION_CNT='DR_MEDIA_IMPRESSION_CNT'
PARTNERSHIP_IMPRESSION_CNT='PARTNERSHIP_IMPRESSION_CNT'
OTHER_EP_IMPRESSION_CNT='OTHER_EP_IMPRESSION_CNT'
OTHER_EP_SESSION_CNT='OTHER_EP_SESSION_CNT'
WEB_VIEW_INV='WEB_VIEW_INV'
OTHER_SOT_SESSION_CNT='OTHER_SOT_SESSION_CNT'
MAKE_NAME='MAKE_NAME'
SF_SESSION_CNT='SF_SESSION_CNT'
OTHER_SOT_IMPRESSION_CNT='OTHER_SOT_IMPRESSION_CNT'
SAVES='SAVES'
INTEREST_EVENTS_1='INTEREST_EVENTS_1'
SF_IMPRESSION_CNT='SF_IMPRESSION_CNT'
VLIST_IMPRESSION_CNT='VLIST_IMPRESSION_CNT'
VLIST_SESSION_CNT='VLIST_SESSION_CNT'
INTEREST_EVENTS_2='INTEREST_EVENTS_2'
BRAND_SEM_SESSION_CNT='BRAND_SEM_SESSION_CNT'
D_NEW_CAR_MERCHANDISING_SCORE='D_NEW_CAR_MERCHANDISING_SCORE'
DEALER_MERCHANDISING_SCORE='DEALER_MERCHANDISING_SCORE'
D_USED_CAR_MERCHANDISING_SCORE='D_USED_CAR_MERCHANDISING_SCORE'
BRAND_SEM_IMPRESSION_CNT='BRAND_SEM_IMPRESSION_CNT'
VDP_SESSION_CNT='VDP_SESSION_CNT'
TABLET_IMPRESSION_CNT='TABLET_IMPRESSION_CNT'
VDP_IMPRESSION_CNT='VDP_IMPRESSION_CNT'
NON_BRAND_SEM_SESSION_CNT='NON_BRAND_SEM_SESSION_CNT'
SEO_SESSION_CNT='SEO_SESSION_CNT'
NON_BRAND_SEM_IMPRESSION_CNT='NON_BRAND_SEM_IMPRESSION_CNT'
DMA='DMA'
PHONE_IMPRESSION_CNT='PHONE_IMPRESSION_CNT'
SRP_SESSION_CNT='SRP_SESSION_CNT'
HP_SESSION_CNT='HP_SESSION_CNT'
SRP_IMPRESSION_CNT='SRP_IMPRESSION_CNT'
DIRECT_SESSION_CNT='DIRECT_SESSION_CNT'
VISITOR_CNT='VISITOR_CNT'
SESSION_CNT='SESSION_CNT'
HP_IMPRESSION_CNT='HP_IMPRESSION_CNT'
DIRECT_IMPRESSION_CNT='DIRECT_IMPRESSION_CNT'
MAX_DAYS_ON_SITE='MAX_DAYS_ON_SITE'
OTHERLSTG_SESSION_CNT='OTHERLSTG_SESSION_CNT'
COMPUTER_IMPRESSION_CNT='COMPUTER_IMPRESSION_CNT'
TOTAL_IMP='TOTAL_IMP'
CAR_DETAIL_PAGE_CNT='CAR_DETAIL_PAGE_CNT'
OTHERLSTG_IMPRESSION_CNT='OTHERLSTG_IMPRESSION_CNT'
MODEL_NAME='MODEL_NAME'
MOBILE_FYC_DETAIL_PAGE_CNT='MOBILE_FYC_DETAIL_PAGE_CNT'
SRP_ALPHA_SESSION_CNT='SRP_ALPHA_SESSION_CNT'
VDP='VDP'
SRP_SPOTLIGHT_SESSION_CNT='SRP_SPOTLIGHT_SESSION_CNT'
SRP_ALPHA_IMPRESSION_CNT='SRP_ALPHA_IMPRESSION_CNT'
CAR_SPOTLIGHT_IMPRESSION_CNT='CAR_SPOTLIGHT_IMPRESSION_CNT'
SRP_SPOTLIGHT_IMPRESSION_CNT='SRP_SPOTLIGHT_IMPRESSION_CNT'
ZIP='ZIP'
SRP_VLIST_SESSION_CNT='SRP_VLIST_SESSION_CNT'
VEHICLE_SKEY='VEHICLE_SKEY'
MOBILE_FYC_SRP_IMPRESSION_CNT='MOBILE_FYC_SRP_IMPRESSION_CNT'
MAX_MILEAGE='MAX_MILEAGE'
SRP_VLIST_IMPRESSION_CNT='SRP_VLIST_IMPRESSION_CNT'
CAR_SRP_IMPRESSION_CNT='CAR_SRP_IMPRESSION_CNT'
CUSTOMER_DURABLE_KEY='CUSTOMER_DURABLE_KEY'
OWNER_ID='OWNER_ID'
CAR_BASE_SRP_IMPRESSION_CNT='CAR_BASE_SRP_IMPRESSION_CNT'
TOTAL_SRPI='TOTAL_SRPI'
KBB_PHOTO_FLG='KBB_PHOTO_FLG'
INCENTIVE_PRICE='INCENTIVE_PRICE'
AVG_MSRP='AVG_MSRP'
AVG_SCARCITY_INDEX='AVG_SCARCITY_INDEX'
AVG_PRICE_TO_MARKET_INDEX='AVG_PRICE_TO_MARKET_INDEX'
AVG_COMMENTS_LENGTH='AVG_COMMENTS_LENGTH'
AVG_PRICE='AVG_PRICE'
VIN='VIN'
CAR_DURABLE_KEY='CAR_DURABLE_KEY'
CAR_ID='CAR_ID'
LISTING_DURABLE_KEY='LISTING_DURABLE_KEY'
;
run;



/**convert missing to zeros**/
data data_file; set data_file;
if SEO_IMPRESSION_CNT eq . then do; SEO_IMPRESSION_CNT=0; end;
if VDP_SEO_ENTRY eq . then do; VDP_SEO_ENTRY=0; end;
if ATC_IND eq . then do; ATC_IND=0; end;
if CREDIT_APP eq . then do; CREDIT_APP=0; end;
if FRONT_LINE_LISTING_IND eq . then do; FRONT_LINE_LISTING_IND=0; end;
if FRONT_LINE_PRO_IND eq . then do; FRONT_LINE_PRO_IND=0; end;
if IMAGE_FLG eq . then do; IMAGE_FLG=0; end;
if INCENTIVE_PRICE_IND eq . then do; INCENTIVE_PRICE_IND=0; end;
if KBB_IND eq . then do; KBB_IND=0; end;
if LISTING_COMMENTS_IND eq . then do; LISTING_COMMENTS_IND=0; end;
if PAYMENT_ON_LISTING_IND eq . then do; PAYMENT_ON_LISTING_IND=0; end;
if POTENTIAL_SALE eq . then do; POTENTIAL_SALE=0; end;
if SPIN360_FLAG eq . then do; SPIN360_FLAG=0; end;
if SPOTLIGHT_IND eq . then do; SPOTLIGHT_IND=0; end;
if SRP_ALP_IMPRESSION_FLG eq . then do; SRP_ALP_IMPRESSION_FLG=0; end;
if SRP_OTH_IMPRESSION_FLG eq . then do; SRP_OTH_IMPRESSION_FLG=0; end;
if SRP_SP_IMPRESSION_FLG eq . then do; SRP_SP_IMPRESSION_FLG=0; end;
if SRP_VLIST_IMPRESSION_FLG eq . then do; SRP_VLIST_IMPRESSION_FLG=0; end;
if VDP_ALPHA_IMP_FLG eq . then do; VDP_ALPHA_IMP_FLG=0; end;
if VDP_BRAND_SEM_ENTRY eq . then do; VDP_BRAND_SEM_ENTRY=0; end;
if VDP_COMPUTER_ENTRY eq . then do; VDP_COMPUTER_ENTRY=0; end;
if VDP_DIRECT_ENTRY eq . then do; VDP_DIRECT_ENTRY=0; end;
if VDP_DR_MEDIA_ENTRY eq . then do; VDP_DR_MEDIA_ENTRY=0; end;
if VDP_HP_ENTRY eq . then do; VDP_HP_ENTRY=0; end;
if VDP_NON_BRAND_SEM_ENTRY eq . then do; VDP_NON_BRAND_SEM_ENTRY=0; end;
if VDP_OTHER_EP_ENTRY eq . then do; VDP_OTHER_EP_ENTRY=0; end;
if VDP_OTHER_SOT_ENTRY eq . then do; VDP_OTHER_SOT_ENTRY=0; end;
if VDP_OTHERLSTG_IMP_FLG eq . then do; VDP_OTHERLSTG_IMP_FLG=0; end;
if VDP_PARTNERSHIP_ENTRY eq . then do; VDP_PARTNERSHIP_ENTRY=0; end;
if VDP_PHONE_ENTRY eq . then do; VDP_PHONE_ENTRY=0; end;
if VDP_SF_ENTRY eq . then do; VDP_SF_ENTRY=0; end;
if VDP_SPOTLIGHT_IMP_FLG eq . then do; VDP_SPOTLIGHT_IMP_FLG=0; end;
if VDP_SRP_ENTRY eq . then do; VDP_SRP_ENTRY=0; end;
if VDP_TABLET_ENTRY eq . then do; VDP_TABLET_ENTRY=0; end;
if VDP_VDP_ENTRY eq . then do; VDP_VDP_ENTRY=0; end;
if VDP_VLIST_IMP_FLG eq . then do; VDP_VLIST_IMP_FLG=0; end;
if VIDEO_FLAG eq . then do; VIDEO_FLAG=0; end;
if VARIANCE_BUCKET eq . then do; VARIANCE_BUCKET=0; end;
if MODEL_YEAR eq . then do; MODEL_YEAR=0; end;
if PRINT eq . then do; PRINT=0; end;
if SRP_OTHERLSTG_SESSION_CNT eq . then do; SRP_OTHERLSTG_SESSION_CNT=0; end;
if BODYSTYLE_NAME eq . then do; BODYSTYLE_NAME=0; end;
if SPOTLIGHT_SESSION_CNT eq . then do; SPOTLIGHT_SESSION_CNT=0; end;
if ALPHA_SESSION_CNT eq . then do; ALPHA_SESSION_CNT=0; end;
if MAP eq . then do; MAP=0; end;
if SRP_OTHERLSTG_IMPRESSION_CNT eq . then do; SRP_OTHERLSTG_IMPRESSION_CNT=0; end;
if ALPHA_IMPRESSION_CNT eq . then do; ALPHA_IMPRESSION_CNT=0; end;
if SPOTLIGHT_IMPRESSION_CNT eq . then do; SPOTLIGHT_IMPRESSION_CNT=0; end;
if VEHSEGMENT eq . then do; VEHSEGMENT=0; end;
if DR_MEDIA_SESSION_CNT eq . then do; DR_MEDIA_SESSION_CNT=0; end;
if PARTNERSHIP_SESSION_CNT eq . then do; PARTNERSHIP_SESSION_CNT=0; end;
if EMAILS eq . then do; EMAILS=0; end;
if LEAD_1 eq . then do; LEAD_1=0; end;
if LEAD_2 eq . then do; LEAD_2=0; end;
if DR_MEDIA_IMPRESSION_CNT eq . then do; DR_MEDIA_IMPRESSION_CNT=0; end;
if PARTNERSHIP_IMPRESSION_CNT eq . then do; PARTNERSHIP_IMPRESSION_CNT=0; end;
if OTHER_EP_IMPRESSION_CNT eq . then do; OTHER_EP_IMPRESSION_CNT=0; end;
if OTHER_EP_SESSION_CNT eq . then do; OTHER_EP_SESSION_CNT=0; end;
if WEB_VIEW_INV eq . then do; WEB_VIEW_INV=0; end;
if OTHER_SOT_SESSION_CNT eq . then do; OTHER_SOT_SESSION_CNT=0; end;
if MAKE_NAME eq . then do; MAKE_NAME=0; end;
if SF_SESSION_CNT eq . then do; SF_SESSION_CNT=0; end;
if OTHER_SOT_IMPRESSION_CNT eq . then do; OTHER_SOT_IMPRESSION_CNT=0; end;
if SAVES eq . then do; SAVES=0; end;
if INTEREST_EVENTS_1 eq . then do; INTEREST_EVENTS_1=0; end;
if SF_IMPRESSION_CNT eq . then do; SF_IMPRESSION_CNT=0; end;
if VLIST_IMPRESSION_CNT eq . then do; VLIST_IMPRESSION_CNT=0; end;
if VLIST_SESSION_CNT eq . then do; VLIST_SESSION_CNT=0; end;
if INTEREST_EVENTS_2 eq . then do; INTEREST_EVENTS_2=0; end;
if BRAND_SEM_SESSION_CNT eq . then do; BRAND_SEM_SESSION_CNT=0; end;
if D_NEW_CAR_MERCHANDISING_SCORE eq . then do; D_NEW_CAR_MERCHANDISING_SCORE=0; end;
if DEALER_MERCHANDISING_SCORE eq . then do; DEALER_MERCHANDISING_SCORE=0; end;
if D_USED_CAR_MERCHANDISING_SCORE eq . then do; D_USED_CAR_MERCHANDISING_SCORE=0; end;
if BRAND_SEM_IMPRESSION_CNT eq . then do; BRAND_SEM_IMPRESSION_CNT=0; end;
if VDP_SESSION_CNT eq . then do; VDP_SESSION_CNT=0; end;
if TABLET_IMPRESSION_CNT eq . then do; TABLET_IMPRESSION_CNT=0; end;
if VDP_IMPRESSION_CNT eq . then do; VDP_IMPRESSION_CNT=0; end;
if NON_BRAND_SEM_SESSION_CNT eq . then do; NON_BRAND_SEM_SESSION_CNT=0; end;
if SEO_SESSION_CNT eq . then do; SEO_SESSION_CNT=0; end;
if NON_BRAND_SEM_IMPRESSION_CNT eq . then do; NON_BRAND_SEM_IMPRESSION_CNT=0; end;
if DMA eq . then do; DMA=0; end;
if PHONE_IMPRESSION_CNT eq . then do; PHONE_IMPRESSION_CNT=0; end;
if SRP_SESSION_CNT eq . then do; SRP_SESSION_CNT=0; end;
if HP_SESSION_CNT eq . then do; HP_SESSION_CNT=0; end;
if SRP_IMPRESSION_CNT eq . then do; SRP_IMPRESSION_CNT=0; end;
if DIRECT_SESSION_CNT eq . then do; DIRECT_SESSION_CNT=0; end;
if VISITOR_CNT eq . then do; VISITOR_CNT=0; end;
if SESSION_CNT eq . then do; SESSION_CNT=0; end;
if HP_IMPRESSION_CNT eq . then do; HP_IMPRESSION_CNT=0; end;
if DIRECT_IMPRESSION_CNT eq . then do; DIRECT_IMPRESSION_CNT=0; end;
if MAX_DAYS_ON_SITE eq . then do; MAX_DAYS_ON_SITE=0; end;
if OTHERLSTG_SESSION_CNT eq . then do; OTHERLSTG_SESSION_CNT=0; end;
if COMPUTER_IMPRESSION_CNT eq . then do; COMPUTER_IMPRESSION_CNT=0; end;
if TOTAL_IMP eq . then do; TOTAL_IMP=0; end;
if CAR_DETAIL_PAGE_CNT eq . then do; CAR_DETAIL_PAGE_CNT=0; end;
if OTHERLSTG_IMPRESSION_CNT eq . then do; OTHERLSTG_IMPRESSION_CNT=0; end;
if MODEL_NAME eq . then do; MODEL_NAME=0; end;
if MOBILE_FYC_DETAIL_PAGE_CNT eq . then do; MOBILE_FYC_DETAIL_PAGE_CNT=0; end;
if SRP_ALPHA_SESSION_CNT eq . then do; SRP_ALPHA_SESSION_CNT=0; end;
if VDP eq . then do; VDP=0; end;
if SRP_SPOTLIGHT_SESSION_CNT eq . then do; SRP_SPOTLIGHT_SESSION_CNT=0; end;
if SRP_ALPHA_IMPRESSION_CNT eq . then do; SRP_ALPHA_IMPRESSION_CNT=0; end;
if CAR_SPOTLIGHT_IMPRESSION_CNT eq . then do; CAR_SPOTLIGHT_IMPRESSION_CNT=0; end;
if SRP_SPOTLIGHT_IMPRESSION_CNT eq . then do; SRP_SPOTLIGHT_IMPRESSION_CNT=0; end;
if ZIP eq . then do; ZIP=0; end;
if SRP_VLIST_SESSION_CNT eq . then do; SRP_VLIST_SESSION_CNT=0; end;
if VEHICLE_SKEY eq . then do; VEHICLE_SKEY=0; end;
if MOBILE_FYC_SRP_IMPRESSION_CNT eq . then do; MOBILE_FYC_SRP_IMPRESSION_CNT=0; end;
if MAX_MILEAGE eq . then do; MAX_MILEAGE=0; end;
if SRP_VLIST_IMPRESSION_CNT eq . then do; SRP_VLIST_IMPRESSION_CNT=0; end;
if CAR_SRP_IMPRESSION_CNT eq . then do; CAR_SRP_IMPRESSION_CNT=0; end;
if CUSTOMER_DURABLE_KEY eq . then do; CUSTOMER_DURABLE_KEY=0; end;
if OWNER_ID eq . then do; OWNER_ID=0; end;
if CAR_BASE_SRP_IMPRESSION_CNT eq . then do; CAR_BASE_SRP_IMPRESSION_CNT=0; end;
if TOTAL_SRPI eq . then do; TOTAL_SRPI=0; end;
if KBB_PHOTO_FLG eq . then do; KBB_PHOTO_FLG=0; end;
if INCENTIVE_PRICE eq . then do; INCENTIVE_PRICE=0; end;
if AVG_MSRP eq . then do; AVG_MSRP=0; end;
if AVG_SCARCITY_INDEX eq . then do; AVG_SCARCITY_INDEX=0; end;
if AVG_PRICE_TO_MARKET_INDEX eq . then do; AVG_PRICE_TO_MARKET_INDEX=0; end;
if AVG_COMMENTS_LENGTH eq . then do; AVG_COMMENTS_LENGTH=0; end;
if AVG_PRICE eq . then do; AVG_PRICE=0; end;
if VIN eq . then do; VIN=0; end;
if CAR_DURABLE_KEY eq . then do; CAR_DURABLE_KEY=0; end;
if CAR_ID eq . then do; CAR_ID=0; end;
if LISTING_DURABLE_KEY eq . then do; LISTING_DURABLE_KEY=0; end;
run;


data data_file; set data_file;
AVG_PRICE_ln=log(AVG_PRICE+1);

if lead_1_dum eq . then do; lead_1_dum=0; end;
if lead_2_dum eq . then do; lead_2_dum=0; end;

label AVG_PRICE_ln='Natural log of AVG_PRICE';
run;


proc freq data=data_file;
tables POTENTIAL_SALE*lead_1_dum POTENTIAL_SALE*lead_2_dum / missing;
run;



ods graphics on;
proc freq data=data_file;
   table lead_2 / plots(only)=freqplot(scale=percent);
run;

proc freq data=data_file;
where lead_2 ne 0;
   table lead_2 / plots(only)=freqplot(scale=percent);
run;


proc univariate data=data_file noprint;
  histogram lead_2 / midpoints = 0 to 5 by 1 vscale = count ;
run;


title 'Histogram of Lead_2';
ods graphics on;
proc univariate data=data_file noprint;
var lead_2;
label vdp='Lead_2';

histogram  / /**normal (color=RED w=5)**/ odstitle=title /**vaxislabel='Label'**/
outhistogram = OutMdpts 


ctext     = blue;
;
run;



title 'Histogram of Lead_2 - excludes zero leads';
ods graphics on;
proc univariate data=data_file noprint;
where lead_2 ne 0;
var lead_2;
label vdp='Lead_2';

histogram  / /**normal (color=RED w=5)**/ odstitle=title /**vaxislabel='Label'**/
outhistogram = OutMdpts 


ctext     = blue;
;
run;
/**
proc print data=OutMdpts;
run;
**/





proc univariate data=data_file;
var vdp;
run;

title 'Histogram of VDP - 99% Quantile';
ods graphics on;
proc univariate data=data_file noprint;
where vdp le 91;
var vdp;
label vdp='VDP';

histogram  / /**normal (color=RED w=5)**/ odstitle=title /**vaxislabel='Label'**/
outhistogram = OutMdpts 


ctext     = blue;
/**inset mean std="Std Dev" / pos = ne format = 6.3;**/
;
run;
/**
proc print data=OutMdpts;
run;
**/




title 'Histogram of VDP - 99% Quantile & excludes zero leads';
ods graphics on;
proc univariate data=data_file noprint;
where vdp le 91 and lead_2 ne 0;;
var vdp;
label vdp='VDP';

histogram  / /**normal (color=RED w=5)**/ odstitle=title /**vaxislabel='Label'**/
outhistogram = OutMdpts 


ctext     = blue;
/**inset mean std="Std Dev" / pos = ne format = 6.3;**/
;
run;




title 'Scatter Plot of Lead_2 and VDP';
proc sgscatter data=data_file; 
matrix lead_2 vdp
/ /**group=atc_ind**/  diagonal=(histogram kernel);
run;


title 'Scatter Plot of Lead_2 and VDP - 99% Quantile & excludes zero leads';
proc sgscatter data=data_file; 
where vdp le 91 and lead_2 ne 0;
matrix lead_2 vdp
/ /**group=atc_ind**/  diagonal=(histogram kernel);
run;





title 'Scatter Plot of Lead_2';
proc sgscatter data=data_file; 
matrix lead_2 MAP
WEB_VIEW_INV
INTEREST_EVENTS_1/**
INTEREST_EVENTS_2
SAVES
CAR_DETAIL_PAGE_CNT
VDP
MOBILE_FYC_DETAIL_PAGE_CNT**/


/ /**group=atc_ind**/  diagonal=(histogram kernel);
run;









%let datain=data_file;
%let labelmodel='Model1';
%let dep=lead_2_dum;
%let indevars= AVG_PRICE_ln
/**Quadrant I vars**/
MAP
WEB_VIEW_INV
SAVES
VDP

/**Quadrant II vars**/
SEO_SESSION_CNT
TOTAL_SRPI
SF_IMPRESSION_CNT
VDP_DR_MEDIA_ENTRY
CAR_SPOTLIGHT_IMPRESSION_CNT

/**Other**/
/**SPOTLIGHT_IND**/
VIDEO_FLAG
KBB_PHOTO_FLG
FRONT_LINE_LISTING_IND




;


title &labelmodel;
proc logistic data=&datain descending /**outest=parm_sedan**/;

    model &dep = &indevars

   / PARMLABEL STB /**RSQUARE  OUTROC=ROC**/; 
output out = /**incent.**/est_data (compress=yes) p= Prob_Est  XBETA=Odds_est_data;

run;
quit;


/**
proc transpose data=parm_sedan out=parm_sedan2; run;
**/

%macro getdeciles(data_sel);
proc sort data=&data_sel; by Prob_Est; run;
data &data_sel;
     set &data_sel NOBS=N;
     length decile 3;
     decile=floor(cnt*10/N+1);
     cnt+1;
     OBS=N;
run;
proc sql;
    create table decile_data as
    select decile,
    avg(Prob_Est) as mean_Prob_Est,
    sum(&dep) as sum_dep,
    count(&dep) as n_dep
    from &data_sel
    group by decile;
run;
quit;
proc print data=decile_data noobs; run;
%mend;

%getdeciles(est_data);




proc corr data=data_file;
var &dep &indevars;
run;





proc genmod data=data_file;
  model lead_2 = &indevars /dist=zip;
  zeromodel lead_2_dum /link = logit;
run;

proc genmod data=data_file;
  model lead_2 = &indevars /dist=zip;
  zeromodel atc_ind /link = logit;
run;


proc genmod data=data_file;
  model lead_2 = &indevars /dist=zip;
  zeromodel  /link = logit;
run;




proc genmod data=data_file;
  model lead_2 =  /dist=zip;
  zeromodel  / link = logit ;
run;
             




proc countreg data=data_file method = qn;
  model lead_2 = &indevars / dist= zip;
  zeromodel lead_2 ~ MAP;
run;






/**
proc genmod data=data_file;
  class atc_ind;
  model lead_2 = vdp atc_ind /dist=zip;
  zeromodel VIDEO_FLAG /link = logit;
run;

proc genmod data=data_file;
  model lead_2 = vdp VIDEO_FLAG /dist=zip;
  zeromodel VIDEO_FLAG /link = logit;
run;
**/








proc reg data=data_file;
where &dep ne 0;
/**id LISTING_DURABLE_KEY**/;
model lead_2 = &indevars 
;
run;
quit;




proc means data=data_file sum n mean median mode min max std clm;
class lead_2_dum;
var vdp;
run;

proc univariate data=data_file;
var vdp;
run;



proc means data=data_file sum n mean median mode min max std clm;
where vdp le 91;
var vdp;
run;

proc means data=data_file sum n mean median mode min max std clm;
where vdp le 91;
class lead_2_dum;
var vdp;
run;
